// <auto-generated />
using Cooking.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cooking.Server.Migrations
{
    [DbContext(typeof(CookingDBContext))]
    [Migration("20250613235513_ChangeDBTables")]
    partial class ChangeDBTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cooking.Server.Models.MeasurementIngredient", b =>
                {
                    b.Property<int>("MeasurementIngredientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeasurementIngredientID"));

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeasurementName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("RecipeID")
                        .HasColumnType("int");

                    b.HasKey("MeasurementIngredientID");

                    b.HasIndex("RecipeID");

                    b.ToTable("MesurementIngredients");

                    b.HasData(
                        new
                        {
                            MeasurementIngredientID = 1,
                            Details = "For Batter",
                            IngredientName = "Flour",
                            MeasurementName = "Cup",
                            Quantity = 2.0,
                            RecipeID = 1
                        });
                });

            modelBuilder.Entity("Cooking.Server.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeID"));

                    b.Property<string>("CookTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrepTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipeTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Yield")
                        .HasColumnType("int");

                    b.HasKey("RecipeID");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeID = 1,
                            CookTime = "20 minutes",
                            Description = "This easy blueberry muffin recipe is our most popular for a reason! It’s quick to make and yields muffins with a moist, tender center bursting with blueberries and a perfectly golden-brown top. When baking this recipe, you can make 10 standard-size muffins, or fill the cups a bit more and make 8 larger muffins with big, beautiful bakery-style tops.",
                            ImageURL = "images/BlueberryMuffin.jpg",
                            Instructions = "mix and cook! ENJOY!",
                            Name = "Blueberry Muffin",
                            PrepTime = "10 minutes",
                            RecipeTag = "Breakfast",
                            Yield = 10
                        });
                });

            modelBuilder.Entity("Cooking.Server.Models.MeasurementIngredient", b =>
                {
                    b.HasOne("Cooking.Server.Models.Recipe", "Recipe")
                        .WithMany("MeasurementIngredients")
                        .HasForeignKey("RecipeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Cooking.Server.Models.Recipe", b =>
                {
                    b.Navigation("MeasurementIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
